#!/bin/sh -e

case "$1" in
    configure)

        if ! id vmops > /dev/null 2>&1 ; then
            adduser --system --home /var/lib/vmops/management --no-create-home \
                --group --disabled-password --shell /bin/sh vmops
                # update me in vmops-client.postinst as well
        fi

	for i in /var/log/vmops/usage
	do
		chmod 0770 $i
		chgrp vmops $i
	done
	
	for i in /etc/vmops/usage/db.properties
	do
		chmod 0640 $i
		chgrp vmops $i
	done
	
    ;;
esac

#DEBHELPER#